### ISSUE TITLE
text-generator-webui API changed.

### ISSUE THREAD

**Issue by cmhamiche** [1b5d/langchain-llm-api#1]
It's port 5000 and the url /api/v1/generate
As for streaming, the port is 5005 and the url is /api/v1/stream

https://github.com/oobabooga/text-generation-webui/blob/main/api-example.py
https://github.com/oobabooga/text-generation-webui/blob/main/api-example-stream.py

I don't need streaming so I simply modified the necessary parts as a quick hack but I though that it would be a good idea to do a bug report.

**Comment by 1b5d** [comment]
You can already specify the host_name and the port using the `host_name` parameter. I updated the README file

But please note that this library is not built for text-generator-webui, but it's built for the [LLM API](https://github.com/1b5d/llm-api) project
