### ISSUE TITLE
Returned embeddings not compatible with vectorstores

### ISSUE THREAD

**Issue by darth-veitcher** [1b5d/langchain-llm-api#2]
I've used this to generate some embeddings from a hosted model and the resulting embeddings returned, once saved into a vectorstore (in my case OpenSearch) don't seem to be compatible with a subsequent search via a retriever.

I get a type error that the index isn't a `k_nn`.

Will post some more detailed logs later on but was wondering if this was a known issue or if you had some working code that illustrated how to use this with a vector store.

**Comment by 1b5d** [comment]
It depends which embeddings you are receiving from the API, this library is written specifically for https://github.com/1b5d/llm-api
