### ISSUE TITLE
Text generation hangs if host_name parameter is used

### ISSUE THREAD

**Issue by ernestp** [1b5d/langchain-llm-api#3]
from langchain_llm_api import LLMAPI, APIEmbeddings

llm = LLMAPI(
    host_name='http://localhost:8000', // << without this line code is working, otherwise hangs
    params={"temp": 0.2},
    verbose=True
)

print(llm("What is the capital of France?"))

**Comment by 1b5d** [comment]
I've updated the README file to document this, thanks!
